name: Docker Image Pull, Tag, and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull xprobe/xinference:v0.15.2

    - name: Tag Docker image
      run: docker tag xprobe/xinference:v0.15.2 registry.cn-hangzhou.aliyuncs.com/acs-uchonor/acs_geocoding_assistant:v0.15.2

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.cn-hangzhou.aliyuncs.com

    - name: Push Docker image
      run: docker push registry.cn-hangzhou.aliyuncs.com/acs-uchonor/acs_geocoding_assistant:v0.15.2
