name: Docker Image Pull, Tag, and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull milvusdb/milvus:master-20241016-4d08eec1

    - name: Tag Docker image
      run: docker tag milvusdb/milvus:master-20241016-4d08eec1 registry.cn-zhangjiakou.aliyuncs.com/compt/milvus:master-20241016-4d08eec1

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.cn-zhangjiakou.aliyuncs.com

    - name: Push Docker image
      run: docker push registry.cn-zhangjiakou.aliyuncs.com/compt/milvus:master-20241016-4d08eec1
