name: Docker Image Pull, Tag, and Push

on: [push]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull Docker image
      run: docker pull nvidia/cuda:12.1.0-devel-ubuntu22.04

    - name: Tag Docker image
      run: docker tag nvidia/cuda:12.1.0-devel-ubuntu22.04 registry.cn-zhangjiakou.aliyuncs.com/compt/cuda:12.1.0-devel-ubuntu22.04

    - name: Log in to Docker registry
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin registry.cn-zhangjiakou.aliyuncs.com

    - name: Push Docker image
      run: docker push registry.cn-zhangjiakou.aliyuncs.com/compt/cuda:12.1.0-devel-ubuntu22.04
